### ISSUE TITLE
Ratelimit not working

### ISSUE THREAD

**Issue by andypl78** [vstakhov/rspamd#1809]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3
### Operation system, CPU, memory and environment:
Debian Jessie
### Description (Please provide a descriptive summary of the issue):
Ratelimit not working for authenticated user.
Authenticated and user cant send more 1 mail per minute.

### Configuration:
postfix main.cf:

```
smtpd_milters                                   = inet:xx.xx.xx.xx:11332
non_smtpd_milters                               = inet:xx.xx.xx.xx:11332
milter_protocol                                 = 6
milter_mail_macros                              = i {mail_addr} {client_addr} {client_name} {auth_authen}
# skip mail without checks if milter will die
milter_default_action                           = accept
milter_rcpt_macros                              = i {rcpt_addr}
```

/etc/rspamd/modules.d/ratelimit.conf
```
ratelimit {
    rates {
        # Limit for all mail per recipient (rate 100 per minute)
        to = "100 / 1m";
        # Limit for all mail per one source ip (rate 15 per minute)
        to_ip = "30 / 2m";
        # Limit for all mail per one source ip and from address (rate 20 per minute)
        to_ip_from = "20 / 1m";
        # Limit for all bounce mail (rate 10 per hour)
        bounce_to = "10 / 1h";
        # Limit for bounce mail per one source ip (rate 5 per hour)
        bounce_to_ip = "5 / 1h";
        # Limit for all mail per authenticated user (rate 5 per minute)
        user = "1 / 1m";
    }
    # If symbol is specified, then it is inserted instead of setting result
    symbol = "R_RATELIMIT";
    whitelisted_rcpts = "postmaster,mailer-daemon";
    max_rcpt = 5;
}

```

**Comment by moisseev** [comment]
You need to use `min` instead of `m`.
It's a bug in the sample configuration. Fixed in the `master`: https://github.com/vstakhov/rspamd/pull/1787/commits/dbd79ccd223d11da63c310a007640742805328f0

**Comment by andypl78** [comment]
And hours are h or else?

**Comment by moisseev** [comment]
That's correct, `h` is for hours.

**Comment by andypl78** [comment]
Still not working in logs  I have this and Rspamd not blocking 

`R_RATELIMIT(0.00){user:1.30;}`

**Comment by fatalbanana** [comment]
If `ratelimit_symbol` is set, ratelimit module inserts a weighted-symbol instead of setting `soft reject` action.

**Comment by andypl78** [comment]
In the documentation and configuration files I can not see the information about ratelimit_symbol
Can you ask for information on what and where you need to set it?

**Comment by andypl78** [comment]
Is it possible to run a sending limit example 1/min and 100/h ?

Like this:

```
# Limit for all mail per authenticated user (rate 5 per minute)
user = "1 / 1min";
user = "100 / 1h";
```

**Comment by fatalbanana** [comment]
No, not readily so unless you were to create and use a functionally identical keyword with a different name. https://rspamd.com/doc/modules/ratelimit.html#user-defined-ratelimits

**Comment by fatalbanana** [comment]
Multiple limits per bucket should [work now](https://github.com/vstakhov/rspamd/commit/9cde61088dbbb7782294296b9a6f86ead00e4eed) in the master/future 1.7.0 version.

~~~
user = "1 / 1min";
user = "100 / 1h";
# is normalised by UCL to:
user = ["1 / 1min", "100 / 1h"];
~~~

... and should work as expected. However, this is a bad example as the first limit is too low; if it were higher it would give the larger limit a chance to match.
